export const SET_BACKGROUND_IMG = 'SET_BACKGROUND_IMG'

export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'

export const SET_EXPIRES_AT = 'SET_EXPIRES_AT'

export const SET_USER_INFO = 'SET_USER_INFO'

export const SET_SHOP_CAT = 'SET_SHOP_CAT'

export const SET_PAY_SHOP = 'SET_PAY_SHOP'

export const SET_ADDRESS_ID = 'SET_ADDRESS_ID'
